### ISSUE TITLE
Adding Consumer in Project Causes SSL Partial Chain Failure

### ISSUE THREAD

**Issue by darthmolen** [skoruba/Duende.IdentityServer.Admin#78]
### Question

Using Docker. Admin works with certificates installed.

When adding a consumer to the project, we get a "SSL Partial Chain Error". identity provider base url is set to "https://sts.skoruba.local". 

As mentioned, admin can be logged into.

![image](https://user-images.githubusercontent.com/533340/173247415-d316ec20-918c-44f8-a390-ee9176b4ce5b.png)

**Comment by darthmolen** [comment]
I got past this doing a number of steps:

Found [this article on stackoverflow](https://github.com/AzureAD/microsoft-identity-web/issues/115) that clued me in on what was going on. Went through the sts code and found the following 2 events:

* OnRedirectToIdentityProvider
* OnRedirectToIdentityProviderForSignOut

added those in.

```csharp
.AddOpenIdConnect("oidc", options =>
{
    options.Authority = identityOptions.OpenId.Authority;
    options.ClientId = identityOptions.OpenId.ClientId;
    options.ClientSecret = identityOptions.OpenId.ClientSecret;
    options.ResponseType = identityOptions.OpenId.ResponseType;
    options.SaveTokens = identityOptions.OpenId.SaveTokens;
    options.RequireHttpsMetadata = identityOptions.OpenId.RequireHttpsMetadata;

    options.GetClaimsFromUserInfoEndpoint = true;

    // https://github.com/AzureAD/microsoft-identity-web/issues/115#issuecomment-618984571
    options.Events = new OpenIdConnectEvents
    {
        OnRedirectToIdentityProvider = context => OnRedirectToIdentityProvider(context, identityOptions),
        OnRedirectToIdentityProviderForSignOut = context => OnRedirectForSignOut(context, identityOptions)
    };
});

/// ...

static Task OnRedirectToIdentityProvider(RedirectContext context, IdentityServerOptions adminConfiguration)
{
    if (!string.IsNullOrEmpty(adminConfiguration.OpenId.SignInRedirectUri))
    {
        var fullUri = $"https://{context.HttpContext.Request.Host}{adminConfiguration.OpenId.SignInRedirectUri}";
        context.ProtocolMessage.RedirectUri = fullUri;
    }

    return Task.CompletedTask;
}

static Task OnRedirectForSignOut(RedirectContext context, IdentityServerOptions adminConfiguration)
{
    if (!string.IsNullOrEmpty(adminConfiguration.OpenId.SignOutRedirectUri))
    {
        var fullUri = $"https://{context.HttpContext.Request.Host}{adminConfiguration.OpenId.SignOutRedirectUri}";
        context.ProtocolMessage.PostLogoutRedirectUri = fullUri;
    }

    return Task.CompletedTask;
}
```

Also had to go source the DockerHelper code to import the ca cert

```csharp
    public class DockerHelpers
    {
        public static void UpdateCaCertificates()
        {
            "update-ca-certificates".Bash();
        }

        public static void ApplyDockerConfiguration(IConfiguration configuration)
        {
            DockerConfiguration dockerConfiguration = configuration.GetSection("DockerConfiguration").Get<DockerConfiguration>();
            if (dockerConfiguration != null && dockerConfiguration.UpdateCaCertificate)
            {
                UpdateCaCertificates();
            }
        }
    }
```

Also had to be sure that the certs were the certs generated by mkcert and were mapped via volumes.

```yaml
  pakilti.identityserver.customer.admin:
    image: ${DOCKER_REGISTRY-}pakiltiidentityservercustomeradmin
    build:
      context: .
      dockerfile: src/Pakilti.IdentityServer.Customer.Admin/Dockerfile
    environment:
      - VIRTUAL_HOST=customer-admin.skoruba.local
      - DockerConfiguration__UpdateCaCertificate=true
    container_name: pakilti-identity-server-customer-admin
    volumes:
      - './shared/nginx/certs/cacerts.crt:/usr/local/share/ca-certificates/cacerts.crt'
    networks:
      identityserverui:
        aliases:
          - customer-admin.skoruba.local
```
